/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/Duck.h"
//#include <iostream>
#include <string.h>

// Initial Test for Rubber Duck.  YayYay
TEST(RubberDuckTest,display){
  RubberDuck my_ralph;
  string except_str="I am a Rubber Duck.";
  EXPECT_EQ(except_str,my_ralph.display()) << "FAIL: display" ;
}
