/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, CREATE YOUR OWN UNIT TESTS ACCORDING
TO THE LAB DOCUMENT.
*/

// Google Test Framework
#include <gtest/gtest.h>
// Project code from the ../src directory
#include "../src/QuackBehavior.h"
#include <string.h>

TEST(QuackBehaviorTest, Constructor) {
  Quack my_quack;
  string expect_str="Quack at 10 decibels.";
  EXPECT_EQ(expect_str,my_quack.quack())<<"FAIL:Quack Constructor!";
}
